# Form implementation generated from reading ui file '.\ui\Design.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 400)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_TTSEngineBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_TTSEngineBox.setGeometry(QtCore.QRect(30, 40, 160, 111))
        self.groupBox_TTSEngineBox.setObjectName("groupBox_TTSEngineBox")
        self.radioButton_OpenAI = QtWidgets.QRadioButton(parent=self.groupBox_TTSEngineBox)
        self.radioButton_OpenAI.setGeometry(QtCore.QRect(20, 50, 140, 21))
        self.radioButton_OpenAI.setObjectName("radioButton_OpenAI")
        self.radioButton_Azure = QtWidgets.QRadioButton(parent=self.groupBox_TTSEngineBox)
        self.radioButton_Azure.setGeometry(QtCore.QRect(20, 70, 101, 21))
        self.radioButton_Azure.setObjectName("radioButton_Azure")
        self.radioButton_CoquiAI = QtWidgets.QRadioButton(parent=self.groupBox_TTSEngineBox)
        self.radioButton_CoquiAI.setGeometry(QtCore.QRect(20, 30, 140, 21))
        self.radioButton_CoquiAI.setObjectName("radioButton_CoquiAI")
        self.textEdit_Results = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit_Results.setGeometry(QtCore.QRect(100, 200, 300, 100))
        self.textEdit_Results.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.TextSelectableByKeyboard|QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.textEdit_Results.setObjectName("textEdit_Results")
        self.groupBox_LanguageBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_LanguageBox.setGeometry(QtCore.QRect(240, 40, 240, 110))
        self.groupBox_LanguageBox.setObjectName("groupBox_LanguageBox")
        self.comboBox_LanguageChoice = QtWidgets.QComboBox(parent=self.groupBox_LanguageBox)
        self.comboBox_LanguageChoice.setGeometry(QtCore.QRect(10, 20, 140, 25))
        self.comboBox_LanguageChoice.setObjectName("comboBox_LanguageChoice")
        self.label_VoiceChoice = QtWidgets.QLabel(parent=self.groupBox_LanguageBox)
        self.label_VoiceChoice.setGeometry(QtCore.QRect(10, 50, 140, 15))
        self.label_VoiceChoice.setObjectName("label_VoiceChoice")
        self.comboBox_VoiceChoice = QtWidgets.QComboBox(parent=self.groupBox_LanguageBox)
        self.comboBox_VoiceChoice.setGeometry(QtCore.QRect(10, 70, 140, 25))
        self.comboBox_VoiceChoice.setObjectName("comboBox_VoiceChoice")
        self.pushButton_VoiceSample = CustomToolTip(parent=self.groupBox_LanguageBox)
        self.pushButton_VoiceSample.setGeometry(QtCore.QRect(160, 70, 31, 25))
        self.pushButton_VoiceSample.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedStates))
        self.pushButton_VoiceSample.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\ui\\../assets/icons/speaker_icon.jpg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_VoiceSample.setIcon(icon)
        self.pushButton_VoiceSample.setObjectName("pushButton_VoiceSample")
        self.pushButton_UserVoice = CustomToolTip(parent=self.groupBox_LanguageBox)
        self.pushButton_UserVoice.setGeometry(QtCore.QRect(200, 70, 31, 25))
        self.pushButton_UserVoice.setToolTipDuration(3)
        self.pushButton_UserVoice.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedStates))
        self.pushButton_UserVoice.setObjectName("pushButton_UserVoice")
        self.progressBar = QtWidgets.QProgressBar(parent=self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(100, 170, 336, 25))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.pushButton_GenerateVoice = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_GenerateVoice.setGeometry(QtCore.QRect(200, 310, 93, 28))
        self.pushButton_GenerateVoice.setObjectName("pushButton_GenerateVoice")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "JIME TTS Generator"))
        self.groupBox_TTSEngineBox.setTitle(_translate("MainWindow", "TTS Engine"))
        self.radioButton_OpenAI.setText(_translate("MainWindow", "OpenAI"))
        self.radioButton_Azure.setText(_translate("MainWindow", "Azure"))
        self.radioButton_CoquiAI.setText(_translate("MainWindow", "BuildIn(CoquiAI)"))
        self.groupBox_LanguageBox.setTitle(_translate("MainWindow", "Language"))
        self.label_VoiceChoice.setText(_translate("MainWindow", "Voice"))
        self.pushButton_VoiceSample.setToolTip(_translate("MainWindow", "Play voice file"))
        self.pushButton_UserVoice.setToolTip(_translate("MainWindow", "<b>Click to select your own voice file<b>"))
        self.pushButton_UserVoice.setText(_translate("MainWindow", "..."))
        self.pushButton_GenerateVoice.setText(_translate("MainWindow", "Generate TTS"))
from src.custom_tooltip import CustomToolTip
